### PR TITLE
Fix a warning `Use of undeclared Var debux.common.util/clojure`

### PR DESCRIPTION
**Pull request by hojinyoo**
a minor fix for cljs

### CODE REVIEW

**Comment by danielcompton** [comment]
Thanks for this! Did this come via debux?

**Comment by hojinyoo** [comment]
actually, the warning was from shadow-cljs, which starts to warn about `extern infer`.

**Review by philoskim — COMMENTED** [review]
Refer to another solution that the author of the original debux library adopted.

https://github.com/philoskim/debux/issues/12

**Comment by superstructor** [comment]
Thanks for the PR @hojinyoo and your comment @philoskim 

Although this solution works and is valid, I also tested deleting the function re @philoskim's comment that the function is no longer used. That works, so I am going to close this PR and just delete the function.

**Pull request closed without merging**
